const Images = {
    redDress : ()=> require('./redDress.jpg') ,
    blueDress : ()=>require('./bluoDress.jpg'),
    bebyDress : ()=>require('./bebyDress.jpg'),
    woomanDress : ()=>require('./woomanDress.jpg'),
    jaketWoman : ()=>require('./jaketWoman.jpg'),
    jaketBeby : ()=>require('./jaketBeby.jpg'),
    jaketBoby : ()=>require('./jaketBoby.jpg'),
    jaketMan : ()=>require('./jaketMan.jpg'),
    bejamaD : ()=>require('./bejamaD.jpg'),
    bejamaS : ()=>require('./bejamaS.jpg'),
    tkM : ()=>require('./tkM.jpg'),
    maN : ()=>require('./maN.jpg'),
    dresS : ()=>require('./dresS.jpg'),
    dressQ: ()=>require('./dressQ.jpg'),
    pincK : ()=>require('./pincK.jpg'),
    menN : ()=>require('./menN.jpg'),
    foR : ()=>require('./foR.jpg'),
    tkemMen: ()=>require('./tkemMen.jpg'),
    hodI : ()=>require('./hodI.jpg'),
    moaQ : ()=>require('./moaQ.jpg'),
    waiF : ()=>require('./waiF.jpg'),
    boY: ()=>require('./boY.jpg'),
    girL : ()=>require('./girL.jpg'),
    waiT : ()=>require('./waiT.jpg'),
    baBy : ()=>require('./baBy.jpg'),
    lplA : ()=>require('./lplA.jpg'),
    pkoQ: ()=>require('./pkoQ.jpg'),
    koL : ()=>require('./koL.jpg'),
    blacK : ()=>require('./blacK.jpg'),
    waitPgama : ()=>require('./waitPgama.jpg'),
    griN : ()=>require('./griN.jpg'),
    bgV : ()=>require('./bgV.jpg'),
    swiM : ()=>require('./swiM.jpg'),
    gygD : ()=>require('./gygD.jpg'),
    hoderA : ()=>require('./hoderA.jpg'),
     douag: ()=>require('./douag.jpg'),
    
}

export default Images